name: CI Workflow
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup repository
        run: npm install

      - name: lint sourcecode
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup repository
        run: npm install
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Run tests
        run: |
          npm run test:coverage > coverage.txt
          coverage=$(node scripts/getCoverageResult.js)
          echo "COVERAGE=$coverage" >> $GITHUB_ENV
      
      - name: Create coverage badge
        run: |
          node scripts/setCoverageBadge.js

      - name: Update README
        run: |
          if [ $(git status | grep -q modified) ];then
            git config --global user.name 'Action'
            git config --global user.email 'action@github.com'
            git stage README.md && git commit -m "[skip ci] Update coverage"
            git push https://${{secrets.REPO_TOKEN}}@github.com/dooomit/typescript-scrapper.git
          fi  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup repository
        run: npm install
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Set BuildStatus
        run: echo "BUILD_STATUS=unknown" >> $GITHUB_ENV
      
      - name: Run build
        run: |
          npm run build
          if [ -f "dist/index.js" ]; then
            echo "BUILD_STATUS=success" >> $GITHUB_ENV
          else
            echo "BUILD_STATUS=failed" >> $GITHUB_ENV
          fi

      - name: Create build status badge
        run: node scripts/setBuildStatusBadge.js

      - name: Update README
        run: |
          if [ $(git status | grep -q modified) ];then
            git config --global user.name 'Action'
            git config --global user.email 'action@github.com'
            git stage README.md && git commit -m "[skip ci] Update build status"
            git push https://${{secrets.REPO_TOKEN}}@github.com/dooomit/typescript-scrapper.git
          fi




      

      


      
