name: CI Workflow
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup repository
        run: npm install

      - name: lint sourcecode
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup repository
        run: npm install
      
      - name: Run tests
        run: |
          SUMMARY="$(npm run test:coverage)"
          echo "NOT IMPLEMENTED"
          echo "COVERAGE=100" >> $GITHUB_ENV
      
      - name: Create coverage badge
        run: node scripts/setCoverageBadge.js

      - name: Update README
        run: git stage README.md && git commit -m "Update coverage" && git push
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup repository
        run: npm install
      
      - name: Set BuildStatus
        run: echo "BUILD_STATUS=unknown" >> $GITHUB_ENV
      
      - name: Run build
        run: |
          npm run build
          if [ -f "dist/index.js" ]; then
            echo "BUILD_STATUS=success" >> $GITHUB_ENV
          else
            echo "BUILD_STATUS=failed" >> $GITHUB_ENV
          fi

      - name: Create build status badge
        run: node scripts/setBuildStatusBadge.js

      - name: Update README
        run: git stage README.md && git commit -m "Update build status" && git push




      

      


      
